export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_PAGINATION_PAGE = "PRODUCT_PAGINATION_PAGE";
export const PRODUCT_PAGINATION_PAGES = "PRODUCT_PAGINATION_PAGES";
export const PRODUCT_PAGINATION_COUNT = "PRODUCT_PAGINATION_COUNT";

export const PRODUCT_FILTERS_RESPONSE = "PRODUCT_FILTERS_RESPONSE";
